---
- name: Check to verify Oracle .patch_storage NFS Shares are unmount
  gather_facts: false
  become: true
  become_user: root
  hosts: plaporaoem1
         pldboraoem1
         dldboran1
         dldboran2
         tldboran1
         tldboran2
         qldboran1
         qldboran2
         pldboran1
         pldboran2
         pldbtrngoran1
         dlapwls1
         tlapwls1
         qlapwls1
         qlapwls2
         qlapwls3
         plapwls1
         plapwls2
         plapwls3
         plaptrngwls1
   
- name: Do not count this as a failure
  ansible.builtin.command: /bin/false
  ignore_errors: true
         
       
  tasks:
    - name: Check current status
      shell: "/usr/local/bin/patch_unmount_check"              
      register: mount_status
    - debug:
       var: mount_status.stdout_lines 
