---
- name: Test connectivity to specific hosts
  hosts:
    - dlapwl1
    - dlaptascob1
    - dlaptascob2
    - dlaptasnfs1
    - dldboran1
    - dldboran2
    - tlaporalb1
    - tlaporalb2
    - tlapwl1
    - tlaptasnfs1
    - tldboran1
    - tldboran2
  gather_facts: false

  pre_tasks:
    - name: Display list of target servers
      ansible.builtin.debug:
        msg: "Testing connectivity for the following hosts: {{ ansible_play_hosts_all }}"
      run_once: true

  tasks:
    - name: Ping target hosts
      ansible.builtin.ping:
