---
- name: Test connectivity to specific hosts
  hosts:
    - dlaporalb1
    - dlaporalb2
    - dlapsftp1
    - dlaptascob1
    - dlaptascob2
    - dlaptasnfs1
    - dlapwl1
    - dldboran1
    - dldboran2
    - dldsadmin1
    - dldsadmin2
    - dldsansible1
    - dldsansible2
    - dldsdev1
    - dldsdev2
    - dldsproto2
    - dldsproto3
    - dlissplunk1
    - paporaoem1
    - paptrngcob1
    - paptrngwl1
    - plaporaoem1
    - plaporalb1
    - plaporalb2
    - plapoemn1
    - plapsftp1
    - plaptascob1
    - plaptascob2
    - plaptasnfs1
    - plaptrngcob1
    - plaptrngwl1
    - plapwl1
    - plapwl2
    - plapwl3
    - pldboemn1
    - pldboran1
    - pldboran2
    - pldboraoem1
    - pldbtrngoran1
    - pldsadmin1
    - pldsansible1
    - pldsmgmt1
    - pldsrhsat1
    - plissecnfs1
    - plisseccen1
    - plissplnkdeploy1
    - plissplnkfwd1
    - plissyslogng
    - plissyslogng1
    - plissyslogng2
    - plissyslogngext.dmz.revenue.int
    - plissyslogngint.dmz.revenue.int
    - plntnetbx1
    - plzirhcap1
    - qlaporalb1
    - qlaporalb2
    - qlapsftp1
    - qlaptascob1
    - qlaptascob2
    - qlaptasnfs1
    - qlapwl1
    - qlapwl2
    - qlapwl3
    - qldboran1
    - qldboran2
    - dldsproto1
    - tlaporalb1
    - tlaporalb2
    - tlaptasnfs1
    - tlapwl1
    - tldboran1
    - tldboran2
  gather_facts: false

  pre_tasks:
    - name: Display list of target servers
      ansible.builtin.debug:
        msg: "Testing connectivity for the following hosts: {{ ansible_play_hosts_all }}"
      run_once: true

  tasks:
    - name: Ping target hosts
      ansible.builtin.ping:
