---
# Playbook to shutdown a Linux Server

# Waring Pause in case of FUBAR   
- name: WARNING this playbook will Shutdown Linux Servers. Cancel immediately if ran in error!
  gather_facts: false
  hosts: dldsproto1
  tasks:
  - name: Pause for 1 minute
    pause:
      minutes: 1

- name: Gather list of Servers and start the Shutdown
  gather_facts: false
  become: true
  become_user: root  
  hosts: dldsproto1
         dldsproto2
         dldsproto3
  
  tasks:
    - name: Issue Shutdown
      command: /sbin/shutdown -h now
      
