---
# Playbook to rotate log files and clean space from the Tanium Client on all RHEL Servers
- name: Tanium Clean
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Run Clean Script
    shell: /usr/local/bin/taniumclean
    #register: status
  #- debug:
     #var: status.stdout_lines
